var lang_ = [{
        "under_title": "DuPont Science and Technologies, LLC",
        "under_timer": "without recordable injures",
        "days": "days",
        "year": "Incidents in 2013 year",
        "issue_type_1": "<h2>MTC</h2>",
        "issue_type_2": "<h2>RWC</h2>",
        "issue_type_3": "<h2>LWC</h2>",
        "0": "tornado",
        "1": "tropical storm",
        "2": "hurricane",
        "3": "severe thunderstorms",
        "4": "thunderstorms",
        "5": "mixed rain and snow",
        "6": "mixed rain and sleet",
        "7": "mixed snow and sleet",
        "8": "freezing drizzle",
        "9": "drizzle",
        "10": "freezing rain",
        "11": "showers",
        "12": "showers",
        "13": "snow flurries",
        "14": "light snow showers",
        "15": "blowing snow",
        "16": "snow",
        "17": "hail",
        "18": "sleet",
        "19": "dust",
        "20": "foggy",
        "21": "haze",
        "22": "smoky",
        "23": "blustery",
        "24": "windy",
        "25": "cold",
        "26": "cloudy",
        "27": "mostly cloudy",
        "28": "mostly cloudy",
        "29": "partly cloudy",
        "30": "partly cloudy",
        "31": "clear (night)",
        "32": "sunny",
        "33": "fair",
        "34": "fair",
        "35": "mixed rain and hail",
        "36": "hot",
        "37": "isolated thunderstorms",
        "38": "scattered thunderstorms",
        "39": "scattered thunderstorms",
        "40": "scattered showers",
        "41": "heavy snow",
        "42": "scattered snow showers",
        "43": "heavy snow",
        "44": "partly cloudy",
        "45": "thundershowers",
        "46": "snow showers",
        "47": "isolated thundershowers",
        "3200": "not available",
        "traffic_text" : ""
    }, {
        "under_title": "ООО «Дюпон Наука и Технологии»",
        "under_timer": "без регистрируемых травм",
        "days": "дней",
        "year": "Инциденты в 2013 году",
        "issue_type_1": "C оказанием медицинской помощи",
        "issue_type_2": "C ограничением трудоспособности",
        "issue_type_3": "C потерей рабочего времени",
        "0": "торнадо",
        "1": "тропический шторм",
        "2": "ураган",
        "3": "severe thunderstorms",
        "4": "thunderstorms",
        "5": "mixed rain and snow",
        "6": "mixed rain and sleet",
        "7": "mixed snow and sleet",
        "8": "freezing drizzle",
        "9": "drizzle",
        "10": "ледяной дождь",
        "11": "ливень",
        "12": "ливень",
        "13": "снегопад",
        "14": "Небольшой снег",
        "15": "метель",
        "16": "снег",
        "17": "град",
        "18": "дождь со снегом",
        "19": "dust",
        "20": "туман",
        "21": "haze",
        "22": "smoky",
        "23": "blustery",
        "24": "ветренно",
        "25": "cold",
        "26": "облачно",
        "27": "переменная облачность",
        "28": "переменная облачность",
        "29": "переменная облачность",
        "30": "переменная облачность",
        "31": "чисто",
        "32": "солнечно",
        "33": "ясная погода",
        "34": "ясная погода",
        "35": "дождь с градом",
        "36": "жара",
        "37": "isolated thunderstorms",
        "38": "scattered thunderstorms",
        "39": "scattered thunderstorms",
        "40": "scattered showers",
        "41": "сильный снегопад",
        "42": "scattered snow showers",
        "43": "сильный снегопад",
        "44": "частичная облачность",
        "45": "Гроза",
        "46": "snow showers",
        "47": "isolated thundershowers",
        "3200": "not available",
        "traffic_text" : ""
        //  ,"" : ""
    }

];
